# Define the build steps
steps:
  # Build the Docker container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/bfawebapp/bfaapp', '.']
  

  # Push the Docker container to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/bfawebapp/bfaapp']

  # Deploy the container to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'bfaapp', '--image', 'gcr.io/bfawebapp/bfaapp', '--platform', 'managed', '--region', 'us-central1']

images:
  - 'gcr.io/bfawebapp/bfaapp'